import os

ESP32_BASE_URL = os.getenv("ESP32_BASE_URL", "http://192.168.1.50")
IRRIGATION_DBNAME = os.getenv("IRRIGATION_DBNAME")
IRRIGATION_DBUSER = os.getenv("IRRIGATION_DBUSER")
IRRIGATION_DBPASSWORD = os.getenv("IRRIGATION_DBPASSWORD")
IRRIGATION_DBHOST = os.getenv("IRRIGATION_DBHOST")
IRRIGATION_DBPORT = int(os.getenv("IRRIGATION_DBPORT", "5432"))
IRRIGATION_SCHEMANAME = os.getenv("IRRIGATION_SCHEMANAME", "public")
IRRIGATION_EVENT_LOG_TABLENAME = os.getenv(
    "IRRIGATION_EVENT_LOG_TABLENAME",
    "irritagion_log",
)
